<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CiudadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ciudades')->insert([
            //CIUDADES DE CONCEPCIÓN
            ['nombre' => 'Concepción', 'departamento_id' => 1],
            ['nombre' => 'Horqueta', 'departamento_id' => 1],
            ['nombre' => 'Belén', 'departamento_id' => 1],
            ['nombre' => 'San Lázaro', 'departamento_id' => 1],
            ['nombre' => 'San Alfredo', 'departamento_id' => 1],
            ['nombre' => 'Azotey', 'departamento_id' => 1],
            ['nombre' => 'Loreto', 'departamento_id' => 1],
            ['nombre' => 'Yby Yaú', 'departamento_id' => 1],
            ['nombre' => 'Ybyrarobaná', 'departamento_id' => 1],
            ['nombre' => 'Villa del Rosario', 'departamento_id' => 1],
            ['nombre' => 'San Carlos del Apa', 'departamento_id' => 1],
            ['nombre' => 'San Pablo', 'departamento_id' => 1],
            ['nombre' => 'Santa Rosa del Aguaray', 'departamento_id' => 1],
            ['nombre' => 'Azotey', 'departamento_id' => 1],
            ['nombre' => 'Yby Yaú', 'departamento_id' => 1],
            ['nombre' => 'Ybyrarobaná', 'departamento_id' => 1],
            ['nombre' => 'Villa del Rosario', 'departamento_id' => 1],
            ['nombre' => 'San Carlos del Apa', 'departamento_id' => 1],
            ['nombre' => 'San Pablo', 'departamento_id' => 1],
            ['nombre' => 'Santa Rosa del Aguaray', 'departamento_id' => 1],

            // CIUDADES DE SAN PEDRO
            ['nombre' => '25 de Diciembre', 'departamento_id' => 2],
            ['nombre' => 'Antequera', 'departamento_id' => 2],
            ['nombre' => 'Chore', 'departamento_id' => 2],
            ['nombre' => 'Colonia Friesland', 'departamento_id' => 2],
            ['nombre' => 'Colonia Navidad', 'departamento_id' => 2],
            ['nombre' => 'Colonia Volendam', 'departamento_id' => 2],
            ['nombre' => 'General Aquino', 'departamento_id' => 2],
            ['nombre' => 'General Resquin', 'departamento_id' => 2],
            ['nombre' => 'Guayaibi', 'departamento_id' => 2],
            ['nombre' => 'Itacurubi', 'departamento_id' => 2],
            ['nombre' => 'Lima', 'departamento_id' => 2],
            ['nombre' => 'Nueva Germania', 'departamento_id' => 2],
            ['nombre' => 'Puerto Rosario', 'departamento_id' => 2],
            ['nombre' => 'Puerto Ybapobó', 'departamento_id' => 2],
            ['nombre' => 'San Estanislao', 'departamento_id' => 2],
            ['nombre' => 'San José del Rosario', 'departamento_id' => 2],
            ['nombre' => 'San Pablo', 'departamento_id' => 2],
            ['nombre' => 'San Pedro', 'departamento_id' => 2],
            ['nombre' => 'Tacuatí', 'departamento_id' => 2],
            ['nombre' => 'Unión', 'departamento_id' => 2],
            ['nombre' => 'Villa del Rosario', 'departamento_id' => 2],
            ['nombre' => 'Yataity del Norte', 'departamento_id' => 2],



            //CIUDADES DE CORDILLERA
            ['nombre' => 'Caacupé', 'departamento_id' => 3],
            ['nombre' => 'Emboscada', 'departamento_id' => 3],
            ['nombre' => 'Eusebio Ayala', 'departamento_id' => 3],
            ['nombre' => 'Isla Pucú', 'departamento_id' => 3],
            ['nombre' => 'Itacurubí de la Cordillera', 'departamento_id' => 3],
            ['nombre' => 'Juan de Mena', 'departamento_id' => 3],
            ['nombre' => 'Loma Grande', 'departamento_id' => 3],
            ['nombre' => 'Mbocayaty del Yhaguy', 'departamento_id' => 3],
            ['nombre' => 'Nueva Colombia', 'departamento_id' => 3],
            ['nombre' => 'Piribebuy', 'departamento_id' => 3],
            ['nombre' => 'Primero de Marzo', 'departamento_id' => 3],
            ['nombre' => 'San Bernardino', 'departamento_id' => 3],
            ['nombre' => 'San José Obrero', 'departamento_id' => 3],
            ['nombre' => 'Santa Elena', 'departamento_id' => 3],
            ['nombre' => 'Tobatí', 'departamento_id' => 3],
            ['nombre' => 'Valenzuela', 'departamento_id' => 3],
            ['nombre' => 'Villa Hayes', 'departamento_id' => 3],
            ['nombre' => 'Arroyos y Esteros', 'departamento_id' => 3],
            ['nombre' => 'Atyrá', 'departamento_id' => 3],
            ['nombre' => 'Altos', 'departamento_id' => 3],
            ['nombre' => 'Caraguatay', 'departamento_id' => 3],
            ['nombre' => 'J. Augusto Saldívar', 'departamento_id' => 3],
            ['nombre' => 'Loma Grande', 'departamento_id' => 3],
            ['nombre' => 'Nueva Colombia', 'departamento_id' => 3],
            ['nombre' => 'Piribebuy', 'departamento_id' => 3],

            //CIUDADES DE GUAIRA
            ['nombre' => 'Borja', 'departamento_id' => 4],
            ['nombre' => 'Capitán Mauricio José Troche', 'departamento_id' => 4],
            ['nombre' => 'Colonia Independencia', 'departamento_id' => 4],
            ['nombre' => 'Dr. Bottrell', 'departamento_id' => 4],
            ['nombre' => 'Félix Pérez Cardozo', 'departamento_id' => 4],
            ['nombre' => 'General Eugenio A. Garay', 'departamento_id' => 4],
            ['nombre' => 'Itapé', 'departamento_id' => 4],
            ['nombre' => 'Iturbe', 'departamento_id' => 4],
            ['nombre' => 'José Fassardi', 'departamento_id' => 4],
            ['nombre' => 'Mbocayaty', 'departamento_id' => 4],
            ['nombre' => 'Natalicio Talavera', 'departamento_id' => 4],
            ['nombre' => 'Ñumí', 'departamento_id' => 4],
            ['nombre' => 'Paso Yobái', 'departamento_id' => 4],
            ['nombre' => 'San Salvador', 'departamento_id' => 4],
            ['nombre' => 'Tacuaras', 'departamento_id' => 4],
            ['nombre' => 'Tebicuary', 'departamento_id' => 4],
            ['nombre' => 'Villarrica', 'departamento_id' => 4],
            ['nombre' => 'Yataity del Guairá', 'departamento_id' => 4],



            // CIUDADES DE CAAGUAZÚ
            ['nombre' => 'Caaguazú', 'departamento_id'=>5],
            ['nombre' => 'Carayaó', 'departamento_id'=>5],
            ['nombre' => 'Coronel Oviedo', 'departamento_id'=>5],
            ['nombre' => 'Doctor Cecilio Báez', 'departamento_id'=>5],
            ['nombre' => 'Doctor Juan Manuel Frutos', 'departamento_id'=>5],
            ['nombre' => 'Doctor Juan Eulogio Estigarribia', 'departamento_id'=>5],
            ['nombre' => 'José Domingo Ocampos', 'departamento_id'=>5],
            ['nombre' => 'La Pastora', 'departamento_id'=>5],
            ['nombre' => 'Mariscal Francisco Solano López', 'departamento_id'=>5],
            ['nombre' => 'Nueva Londres', 'departamento_id'=>5],
            ['nombre' => 'Raúl Arsenio Oviedo', 'departamento_id'=>5],
            ['nombre' => 'Repatriación', 'departamento_id'=>5],
            ['nombre' => 'San Joaquín', 'departamento_id'=>5],
            ['nombre' => 'San José de los Arroyos', 'departamento_id'=>5],
            ['nombre' => 'Santa Rosa del Mbutuy', 'departamento_id'=>5],
            ['nombre' => 'Simón Bolívar', 'departamento_id'=>5],
            ['nombre' => 'Tres de Febrero', 'departamento_id'=>5],
            ['nombre' => 'Vaquería', 'departamento_id'=>5],
            ['nombre' => 'Yhú', 'departamento_id'=>5],

            // CIUDADES DE CAAZAPÁ
            ['nombre' => 'Abaí', 'departamento_id'=>6],
            ['nombre' => 'Buena Vista', 'departamento_id'=>6],
            ['nombre' => 'Caazapá', 'departamento_id'=>6],
            ['nombre' => 'Doctor Moisés S. Bertoni', 'departamento_id'=>6],
            ['nombre' => 'Fulgencio Yegros', 'departamento_id'=>6],
            ['nombre' => 'General Higinio Morínigo', 'departamento_id'=>6],
            ['nombre' => 'Maciel', 'departamento_id'=>6],
            ['nombre' => 'Mbuyapey', 'departamento_id'=>6],
            ['nombre' => 'San Juan Nepomuceno', 'departamento_id'=>6],
            ['nombre' => 'Tavaí', 'departamento_id'=>6],
            ['nombre' => 'Yuty', 'departamento_id'=>6],
            ['nombre' => '3 de mayo', 'departamento_id'=>6],

            // CIUDADES DE ITAPÚA
            ['nombre' => 'Alto Verá', 'departamento_id'=>7],
            ['nombre' => 'Bella Vista', 'departamento_id'=>7],
            ['nombre' => 'Cambyretá', 'departamento_id'=>7],
            ['nombre' => 'Capitán Meza', 'departamento_id'=>7],
            ['nombre' => 'Carlos Antonio López', 'departamento_id'=>7],
            ['nombre' => 'Carmen del Paraná', 'departamento_id'=>7],
            ['nombre' => 'Coronel Bogado', 'departamento_id'=>7],
            ['nombre' => 'Edelira', 'departamento_id'=>7],
            ['nombre' => 'Encarnación', 'departamento_id'=>7],
            ['nombre' => 'Fram', 'departamento_id'=>7],
            ['nombre' => 'General Artigas', 'departamento_id'=>7],
            ['nombre' => 'General Delgado', 'departamento_id'=>7],
            ['nombre' => 'Hohenau', 'departamento_id'=>7],
            ['nombre' => 'Itapúa Poty', 'departamento_id'=>7],
            ['nombre' => 'Jesús', 'departamento_id'=>7],
            ['nombre' => 'José Leandro Oviedo', 'departamento_id'=>7],
            ['nombre' => 'La Paz', 'departamento_id'=>7],
            ['nombre' => 'Mayor Otaño', 'departamento_id'=>7],
            ['nombre' => 'Natalio', 'departamento_id'=>7],
            ['nombre' => 'Nueva Alborada', 'departamento_id'=>7],
            ['nombre' => 'Obligado', 'departamento_id'=>7],
            ['nombre' => 'Pirapó', 'departamento_id'=>7],
            ['nombre' => 'San Cosme y Damián', 'departamento_id'=>7],
            ['nombre' => 'San Juan del Paraná', 'departamento_id'=>7],
            ['nombre' => 'San Pedro del Paraná', 'departamento_id'=>7],
            ['nombre' => 'San Rafael del Paraná', 'departamento_id'=>7],
            ['nombre' => 'Tomás Romero Pereira', 'departamento_id'=>7],
            ['nombre' => 'Trinidad', 'departamento_id'=>7],
            ['nombre' => 'Yatytay', 'departamento_id'=>7],

            // CIUDADES DE MISIONES
            ['nombre' => 'Ayolas', 'departamento_id'=>8],
            ['nombre' => 'Colonia Alejo García', 'departamento_id' => 8],
            ['nombre' => 'San Ignacio', 'departamento_id'=>8],
            ['nombre' => 'San Juan Bautista', 'departamento_id'=>8],
            ['nombre' => 'San Miguel', 'departamento_id'=>8],
            ['nombre' => 'San Patricio', 'departamento_id'=>8],
            ['nombre' => 'Santa María', 'departamento_id'=>8],
            ['nombre' => 'Santa Rosa', 'departamento_id'=>8],
            ['nombre' => 'Santiago', 'departamento_id'=>8],
            ['nombre' => 'Villa Florida', 'departamento_id'=>8],
            ['nombre' => 'Yabebyry', 'departamento_id'=>8],
            ['nombre' => 'Yacaré Curuguaty', 'departamento_id'=>8],

            // CIUDADES DE PARAGUARÍ
            ['nombre' => 'Acahay', 'departamento_id'=>9],
            ['nombre' => 'Caballero', 'departamento_id'=>9],
            ['nombre' => 'Caapucú', 'departamento_id'=>9],
            ['nombre' => 'Carapeguá', 'departamento_id'=>9],
            ['nombre' => 'Escobar', 'departamento_id'=>9],
            ['nombre' => 'General Bernardino Caballero', 'departamento_id'=>9],
            ['nombre' => 'La Colmena', 'departamento_id'=>9],
            ['nombre' => 'Paraguarí', 'departamento_id'=>9],
            ['nombre' => 'Pirayú', 'departamento_id'=>9],
            ['nombre' => 'Quiindy', 'departamento_id'=>9],
            ['nombre' => 'Quyquyhó', 'departamento_id'=>9],
            ['nombre' => 'San Roque González de Santa Cruz', 'departamento_id'=>9],
            ['nombre' => 'Sapucai', 'departamento_id'=>9],
            ['nombre' => 'Tebicuarymí', 'departamento_id'=>9],
            ['nombre' => 'Yaguarón', 'departamento_id'=>9],
            ['nombre' => 'Ybycuí', 'departamento_id'=>9],
            ['nombre' => 'Ybytimí', 'departamento_id'=>9],
            ['nombre' => 'Yby Yaú', 'departamento_id'=>9],

            // CIUDADES DE ALTO PARANÁ
            ['nombre' => 'Ciudad del Este', 'departamento_id'=>10],
            ['nombre' => 'Doctor Juan León Mallorquín', 'departamento_id'=>10],
            ['nombre' => 'Doctor Raúl Peña', 'departamento_id'=>10],
            ['nombre' => 'Doctor Rogelio Insfrán', 'departamento_id'=>10],
            ['nombre' => 'Hernandarias', 'departamento_id'=>10],
            ['nombre' => 'Iruña', 'departamento_id'=>10],
            ['nombre' => 'Itakyry', 'departamento_id'=>10],
            ['nombre' => 'Juan E. O’Leary', 'departamento_id'=>10],
            ['nombre' => 'Los Cedrales', 'departamento_id'=>10],
            ['nombre' => 'Mbaracayú', 'departamento_id'=>10],
            ['nombre' => 'Minga Guazú', 'departamento_id'=>10],
            ['nombre' => 'Minga Porá', 'departamento_id'=>10],
            ['nombre' => 'Ñacunday', 'departamento_id'=>10],
            ['nombre' => 'Presidente Franco', 'departamento_id'=>10],
            ['nombre' => 'San Alberto', 'departamento_id'=>10],
            ['nombre' => 'San Cristóbal', 'departamento_id'=>10],
            ['nombre' => 'Santa Fe del Paraná', 'departamento_id'=>10],
            ['nombre' => 'Santa Rita', 'departamento_id'=>10],
            ['nombre' => 'Santa Rosa del Monday', 'departamento_id'=>10],
            ['nombre' => 'Tavapy', 'departamento_id'=>10],
            ['nombre' => 'Yguazú', 'departamento_id'=>10],

            // CIUDADES DE CENTRAL
            ['nombre' => 'Areguá', 'departamento_id'=>11],
            ['nombre' => 'Capiatá', 'departamento_id'=>11],
            ['nombre' => 'Fernando de la Mora', 'departamento_id'=>11],
            ['nombre' => 'Guarambaré', 'departamento_id'=>11],
            ['nombre' => 'Itá', 'departamento_id'=>11],
            ['nombre' => 'Itauguá', 'departamento_id'=>11],
            ['nombre' => 'J. Augusto Saldívar', 'departamento_id'=>11],
            ['nombre' => 'Lambaré', 'departamento_id'=>11],
            ['nombre' => 'Limpio', 'departamento_id'=>11],
            ['nombre' => 'Luque', 'departamento_id'=>11],
            ['nombre' => 'Mariano Roque Alonso', 'departamento_id'=>11],
            ['nombre' => 'Nueva Italia', 'departamento_id'=>11],
            ['nombre' => 'San Antonio', 'departamento_id'=>11],
            ['nombre' => 'San Lorenzo', 'departamento_id'=>11],
            ['nombre' => 'Villa Elisa', 'departamento_id'=>11],
            ['nombre' => 'Villeta', 'departamento_id'=>11],
            ['nombre' => 'Ypacaraí', 'departamento_id'=>11],
            ['nombre' => 'Ypané', 'departamento_id'=>11],

            // CIUDADES DE ÑEEMBUCÚ
            ['nombre' => 'Alberdi', 'departamento_id'=>12],
            ['nombre' => 'Cerrito', 'departamento_id'=>12],
            ['nombre' => 'Desmochados', 'departamento_id'=>12],
            ['nombre' => 'General José Eduvigis Díaz', 'departamento_id'=>12],
            ['nombre' => 'Guazú Cuá', 'departamento_id'=>12],
            ['nombre' => 'Humaitá', 'departamento_id'=>12],
            ['nombre' => 'Isla Umbú', 'departamento_id'=>12],
            ['nombre' => 'Laureles', 'departamento_id'=>12],
            ['nombre' => 'Mayor José J. Martínez', 'departamento_id'=>12],
            ['nombre' => 'Paso de Patria', 'departamento_id'=>12],
            ['nombre' => 'San Juan Bautista del Ñeembucú', 'departamento_id'=>12],
            ['nombre' => 'Tacuaras', 'departamento_id'=>12],
            ['nombre' => 'Villa Franca', 'departamento_id'=>12],
            ['nombre' => 'Villa Oliva', 'departamento_id'=>12],
            ['nombre' => 'Villa Paranacito', 'departamento_id'=>12],
            ['nombre' => 'Villa Salto del Guairá', 'departamento_id'=>12],
            ['nombre' => 'Villalbín', 'departamento_id'=>12],

            // CIUDADES DE AMAMBAY
            ['nombre' => 'Bella Vista', 'departamento_id'=>13],
            ['nombre' => 'Capitán Bado', 'departamento_id'=>13],
            ['nombre' => 'Capitán Carmelo Peralta', 'departamento_id'=>13],
            ['nombre' => 'Concepción', 'departamento_id'=>13],
            ['nombre' => 'Corpus Christi', 'departamento_id'=>13],
            ['nombre' => 'Curuguaty', 'departamento_id'=>13],
            ['nombre' => 'General Francisco Caballero Álvarez', 'departamento_id'=>13],
            ['nombre' => 'General José Eduvigis Díaz', 'departamento_id'=>13],
            ['nombre' => 'Itanará', 'departamento_id'=>13],
            ['nombre' => 'Karapaí', 'departamento_id'=>13],
            ['nombre' => 'Katueté', 'departamento_id'=>13],
            ['nombre' => 'La Paloma', 'departamento_id'=>13],
            ['nombre' => 'Loma Grande', 'departamento_id'=>13],
            ['nombre' => 'Loma Plata', 'departamento_id'=>13],
            ['nombre' => 'Maracaná', 'departamento_id'=>13],
            ['nombre' => 'Nueva Esperanza', 'departamento_id'=>13],
            ['nombre' => 'Pedro Juan Caballero', 'departamento_id'=>13],
            ['nombre' => 'Puerto Diana', 'departamento_id'=>13],
            ['nombre' => 'Puerto Pinasco', 'departamento_id'=>13],
            ['nombre' => 'Salto del Guairá', 'departamento_id'=>13],
            ['nombre' => 'San Alberto', 'departamento_id'=>13],
            ['nombre' => 'San Carlos del Apa', 'departamento_id'=>13],
            ['nombre' => 'San Estanislao', 'departamento_id'=>13],
            ['nombre' => 'San Lázaro', 'departamento_id'=>13],
            ['nombre' => 'San Pedro del Paraná', 'departamento_id'=>13],
            ['nombre' => 'San Rafael del Paraná', 'departamento_id'=>13],
            ['nombre' => 'Santa Rosa del Aguaray', 'departamento_id'=>13],

            // CIUDADES DE CANINDEYÚ
            ['nombre' => 'Arroyito', 'departamento_id'=>14],
            ['nombre' => 'Azotey', 'departamento_id'=>14],
            ['nombre' => 'Bella Vista', 'departamento_id'=>14],
            ['nombre' => 'Bella Vista Norte', 'departamento_id'=>14],
            ['nombre' => 'Capitán Bado', 'departamento_id'=>14],
            ['nombre' => 'Doctor Cecilio Báez', 'departamento_id'=>14],
            ['nombre' => 'Doctor J. Eulogio Estigarribia', 'departamento_id'=>14],
            ['nombre' => 'Doctor Juan Manuel Frutos', 'departamento_id'=>14],
            ['nombre' => 'Doctor Raúl Peña', 'departamento_id'=>14],
            ['nombre' => 'General Francisco Caballero Álvarez', 'departamento_id'=>14],
            ['nombre' => 'Itanará', 'departamento_id'=>14],
            ['nombre' => 'Katueté', 'departamento_id'=>14],
            ['nombre' => 'La Paloma', 'departamento_id'=>14],

            // CIUDADES DE PRESIDENTE HAYES
            ['nombre' => 'Benjamín Aceval', 'departamento_id'=>15],
            ['nombre' => 'Doctor Juan Manuel Frutos', 'departamento_id'=>15],
            ['nombre' => 'Doctor Juan León Mallorquín', 'departamento_id'=>15],
            ['nombre' => 'Doctor Pedro P. Peña', 'departamento_id'=>15],
            ['nombre' => 'Doctor Raúl Peña', 'departamento_id'=>15],
            ['nombre' => 'General Bruguez', 'departamento_id'=>15],
            ['nombre' => 'General Elizardo Aquino', 'departamento_id'=>15],
            ['nombre' => 'General Eugenio A. Garay', 'departamento_id'=>15],
            ['nombre' => 'Ismael Rolón Silvero', 'departamento_id'=>15],
            ['nombre' => 'José Falcón', 'departamento_id'=>15],
            ['nombre' => 'Mcal. Estigarribia', 'departamento_id'=>15],
            ['nombre' => 'Nanawa', 'departamento_id'=>15],
            ['nombre' => 'Pozo Colorado', 'departamento_id'=>15],
            ['nombre' => 'Puerto Pinasco', 'departamento_id'=>15],
            ['nombre' => 'Teniente Esteban Martínez', 'departamento_id'=>15],
            ['nombre' => 'Tte. Irala Fernández', 'departamento_id'=>15],
            ['nombre' => 'Villa Hayes', 'departamento_id'=>15],

            //CIUDADES DE BOQUERÓN
            ['nombre' => 'Filadelfia', 'departamento_id'=>16],
            ['nombre' => 'Mariscal Estigarribia', 'departamento_id'=>16],
            ['nombre' => 'Dr. Pedro P. Peña', 'departamento_id'=>16],
            ['nombre' => 'Loma Plata', 'departamento_id'=>16],
            ['nombre' => 'General Eugenio A. Garay', 'departamento_id'=>16],
            ['nombre' => 'Capitán Joel Estigarribia', 'departamento_id'=>16],
            ['nombre' => 'Colonia Neuland', 'departamento_id'=>16],
            ['nombre' => 'Teniente Primero Irala Fernández', 'departamento_id'=>16],

            //CIUDADES DE ALTO PARAGUAY
            ['nombre' => 'Fuerte Olimpo', 'departamento_id'=>17],
            ['nombre' => 'Puerto Casado', 'departamento_id'=>17],
            ['nombre' => 'Bahía Negra', 'departamento_id'=>17],
            ['nombre' => 'Carmen del Paraná', 'departamento_id'=>17],
            ['nombre' => 'Mayor Pablo Lagerenza', 'departamento_id'=>17],
            ['nombre' => 'Puerto Pinasco', 'departamento_id'=>17],
            ['nombre' => 'Puerto La Esperanza', 'departamento_id'=>17],
            ['nombre' => 'Puerto Elsa', 'departamento_id'=>17],
            ['nombre' => 'Puerto La Victoria', 'departamento_id'=>17],
            ['nombre' => 'Puerto Guaraní', 'departamento_id'=>17],
            ['nombre' => 'Puerto Diana', 'departamento_id'=>17],
            ['nombre' => 'Puerto Leda', 'departamento_id'=>17],
            ['nombre' => 'Puerto Esperanza', 'departamento_id'=>17],
            ['nombre' => 'Puerto Indio', 'departamento_id'=>17],
            ['nombre' => 'Puerto Mayor Otano', 'departamento_id'=>17],
            ['nombre' => 'Puerto Murta', 'departamento_id'=>17],
            ['nombre' => 'Puerto Pinasco', 'departamento_id'=>17],
            ['nombre' => 'Puerto Sastre', 'departamento_id'=>17],
            ['nombre' => 'Puerto Unión', 'departamento_id'=>17],
            ['nombre' => 'Puerto Vallemí', 'departamento_id'=>17],
            ['nombre' => 'Puerto Ygauazú', 'departamento_id'=>17],
            ['nombre' => 'Puerto Ypejhú', 'departamento_id'=>17],
            ['nombre' => 'Puerto Zanotti', 'departamento_id'=>17],
            ['nombre' => 'Teniente Irala Fernández', 'departamento_id'=>17],
            ['nombre' => 'Villa Hayes', 'departamento_id'=>17],
            ['nombre' => 'Villa Oliva', 'departamento_id'=>17],



        ]);
    }
}
